development:
  adapter: postgresql
  database: singlefile_development
  pool: 20
  checkout_timeout: 5

production:
  adapter: postgresql
  database: singlefile_production
  pool: 20
  checkout_timeout: 5
